### PR TITLE
Add array data and queries

### PR DESCRIPTION
**Pull request by samtstern**
Mirrors https://github.com/firebase/snippets-web/pull/7

### CODE REVIEW

**Comment by samtstern** [comment]
**DO NOT MERGE** this does not actually compile yet (I think the iOS SDK has yet to be released)

cc @morganchen12 @ulukaya can we add Travis to this repo?

**Comment by morganchen12** [comment]
Yes, we can. I'll work on adding Travis.

**Comment by samtstern** [comment]
@morganchen12 do you know if the SDK for this was released?

**Comment by morganchen12** [comment]
This was released in M30. https://firebase.google.com/support/release-notes/ios

**Pull request merged**
