### PR TITLE
Add missing import

### PR DESCRIPTION
**Pull request by ferrufino**
Xcode Version 10.0
Swift 4.2

### CODE REVIEW

**Comment by ferrufino** [comment]
I signed it!

**Comment by morganchen12** [comment]
@ferrufino this should compile without explicitly adding `import FirebaseFirestore`. What compiler error are you seeing?

**Comment by ferrufino** [comment]
@morganchen12 It showed an error saying: **Use of unresolved identifier 'Firestore'**, once I added the import it solved it. I'm setting up Firestore on my own app, if it helps somehow mentioning this. 

I wanted to update this hoping the documentation of [Getting started](https://firebase.google.com/docs/firestore/quickstart) would be updated with this import needed.

**Comment by morganchen12** [comment]
Our other sample, which builds on Travis, is able to build fine without adding the extra import:

https://github.com/firebase/quickstart-ios/blob/master/firestore/FirestoreExample/AppDelegate.swift
https://travis-ci.org/firebase/quickstart-ios/jobs/491769888

How are you integrating Firestore?

**Comment by obitodarky** [comment]
> @morganchen12 It showed an error saying: **Use of unresolved identifier 'Firestore'**, once I added the import it solved it. I'm setting up Firestore on my own app, if it helps somehow mentioning this.
> 
> I wanted to update this hoping the documentation of [Getting started](https://firebase.google.com/docs/firestore/quickstart) would be updated with this import needed.

Have you added the correct pods in your Podfile?

**Comment by ferrufino** [comment]
Yes of course @obitodarky. I'll just close this since it builds on Travis.

**Pull request closed without merging**
