### PR TITLE
Add travis

### LINKED ISSUE #4: Add Travis CI for build verification
Code in this repository should be automatically verified for at least compilation, and correctness as a bonus.  Travis would be ideal for consistency but whatever is easiest.

### PR DESCRIPTION
**Pull request by morganchen12**
Fixes #4.

### CODE REVIEW

**Comment by samtstern** [comment]
Thank you!

**Comment by samtstern** [comment]
@morganchen12 ❤️

**Comment by samtstern** [comment]
@morganchen12 I think we're in a bit of Travis purgatory right now...

**Comment by morganchen12** [comment]
Are we unable to add new travis projects?

**Comment by samtstern** [comment]
Yeah that's the situation right now.

**Pull request merged**
